FROM python:3
ENV PYTHONUNBUFFERED 1 
RUN pip install django
RUN pip install mysqlclient
RUN pip install python-xbrl
RUN pip install urllib3
RUN pip install tqdm
RUN pip install requests
RUN pip install pandas
RUN pip install autopep8
RUN pip install apscheduler
RUN pip install validate_email
RUN pip install PyJWT